version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/package.json:/app/package.json
      - ./client/package-lock.json:/app/package-lock.json
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npm run dev
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - webapp-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: sh -c "npx prisma migrate deploy && npm run dev"
    depends_on:
      - postgres
      - redis
    networks:
      - webapp-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - webapp-network

  postgres:
    image: postgres:15
    container_name: webapp-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=spbappadmin
      - POSTGRES_PASSWORD=spbapppassword
      - POSTGRES_DB=spbappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webapp-network

  adminer:
    image: adminer
    container_name: webapp-adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - webapp-network

volumes:
  postgres_data:
  redis-data:

networks:
  webapp-network:
    driver: bridge
