FROM node:18

WORKDIR /app

COPY package*.json ./

# Installa tutte le dipendenze, comprese le devDependencies (default se NODE_ENV non è impostato a production)
RUN npm install

COPY . .

# Genera i client Prisma (molto importante, va fatto dopo aver copiato il codice)
RUN npx prisma generate

# Avvia il server con nodemon per hot reload
CMD ["npm", "run", "dev"]
